// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uocxfumnfmjauhtgvwly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvY3hmdW1uZm1qYXVodGd2d2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5MzI3NDIsImV4cCI6MjA4NDUwODc0Mn0.WsjW-9KV5kd-NyGLMXkghxIfPEbJf3cbfkgxFRSMy7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});